inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

plugins:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snippets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/Rakefile'
    - 'spec/rails_helper.rb'
    - 'spec/factories/*.rb'

Style/MultilineBlockChain:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# Enforce single quotes everywhere except in specs (because there's a lot of
# human text with apostrophes in spec names, and using double quotes for all
# of those is more consistent. There shouldn't be much human-readable text in
# the application code: that is better moved to the locale files.
Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'spec/**/*'

RSpec/AnyInstance:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  # This is only 2 more than the default, and the transgressor just proves that rubocop can't count.
  Max: 27
  Exclude:
    - 'config/environments/*'
    - 'Guardfile'
    - 'app/admin/*'
    - 'lib/tasks/*'
    - 'spec/**/*'

RSpec/ExampleLength:
  Max: 150

RSpec/HookArgument:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 20

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 8

RSpec/ScatteredSetup:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    # The DescribeClass cop has been disabled as it is insists that the describe
    # block contain the name of the tested class.  However rswag is using this
    # text as part of the API documentation generated from these tests.
    - 'spec/api/**/*_spec.rb'

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/VariableName:
  Exclude:
    # Authorization 'method' needs to be defined for rswag
    - 'spec/api/**/*_spec.rb'

RSpec/BeEq:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

RSpec/MetadataStyle:
  Enabled: false

RSpec/MatchArray:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/SaveBang:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

# In a view spec, the top level describe must be the view that is rendered
RSpec/MultipleDescribes:
  Exclude:
    - 'spec/views/handovers/columns_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

# Below here is the set of (arbitrary) style failures against the govuk versions
Style/WordArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/EachForSimpleLoop:
  Enabled: false

# We don't want anyone to have to know that an `if` statement evaluates to nil if none of its conditions are met,
# so we allow `else  nil` so it's crystal clear
Style/EmptyElse:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either
