{{- if .Values.cronjobs.mailbox_register_import.enabled }}
{{- $cronjobName := "mailbox-register-import" }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronjobName }}
spec:
  schedule: {{ .Values.cronjobs.mailbox_register_import.schedule }}
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ index .Values "generic-service" "serviceAccountName" }}
          restartPolicy: OnFailure
          securityContext:
            {{- with index .Values "generic-service" }}{{ toYaml .podSecurityContext | nindent 12 }}{{ end }}
          containers:
          - name: {{ $cronjobName }}
            image: {{ with index .Values "generic-service" }}{{ .image.repository }}:{{ .image.tag }}{{ end }}
            imagePullPolicy: Always
            securityContext:
              {{- with index .Values "generic-service" }}{{ toYaml .securityContext | nindent 14 }}{{ end }}
            command: ["sh", "-c", "bundle exec rake import:local_delivery_units:process"]
              {{- include "moic-helpers.envs_without_prometheus_metrics" . | nindent 12 }}
            resources:
              {{- toYaml .Values.cronjob_resources | nindent 14 }}
---
{{- end }}
