{{- if .Values.cronjobs.recalculate_handover_dates.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: recalculate-handover-dates
spec:
  schedule: "30 6 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          serviceAccountName: {{ index .Values "generic-service" "serviceAccountName" }}
          restartPolicy: OnFailure
          securityContext:
            {{- with index .Values "generic-service" }}{{ toYaml .podSecurityContext | nindent 12 }}{{ end }}
          containers:
          - name: recalculate-handover-dates
            image: {{ with index .Values "generic-service" }}{{ .image.repository }}:{{ .image.tag }}{{ end }}
            imagePullPolicy: Always
            securityContext:
              {{- with index .Values "generic-service" }}{{ toYaml .securityContext | nindent 14 }}{{ end }}
            command: ["sh", "-c", "bundle exec rake recalculate_handover_dates"]
              {{- include "moic-helpers.envs_without_prometheus_metrics" . | nindent 12 }}
            resources:
              limits:
                memory: 1000Mi
                cpu: 1000m
              requests:
                memory: 500Mi
                cpu: 50m
---
{{- end }}
