SERVICE_DESK_NUMBER = '0800 917 5148'.freeze
SERVICE_DESK_EXTENSION = '6598'.freeze
SERVICE_EMAIL_ADDRESS = ENV['SERVICE_EMAIL_ADDRESS'].freeze
DEFAULT_UPCOMING_HANDOVER_WINDOW_DURATION = 8 * 7 # 8 weeks
