USE_APR_2023_HANDOVER_POLICY_CHANGES = ENV.fetch('USE_APR_2023_HANDOVER_POLICY_CHANGES', '').strip == '1'
USE_EVENTS_TO_PUSH_HANDOVER_TO_DELIUS = ENV.fetch('USE_EVENTS_TO_PUSH_HANDOVER_TO_DELIUS', '').strip == '1'
