USE_RISKS_API = ENV.fetch('USE_RISKS_API', '').strip == '1'
USE_ALERTS_IN_ALLOC_MSG = ENV.fetch('USE_ALERTS_IN_ALLOC_MSG', '').strip == '1'
USE_MAPPA_IN_ALLOC_MSG = ENV.fetch('USE_MAPPA_IN_ALLOC_MSG', '').strip == '1'
USE_APR_2023_HANDOVER_POLICY_CHANGES = ENV.fetch('USE_APR_2023_HANDOVER_POLICY_CHANGES', '').strip == '1'
