apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: offender-manager-process-movements
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
            - name: process-movements
              image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/offender-management/offender-management-allocation-manager:latest
              imagePullPolicy: Always
              command: ['sh', '-c', "bundle exec rake movements:process"]
              resources:
                limits:
                  memory: "1500Mi"
                  cpu: "1000m"
                requests:
                  memory: "500Mi"
                  cpu: "100m"
              envFrom:
                - configMapRef:
                    name: shared-environment
                - secretRef:
                    name: allocation-manager-secrets
                - secretRef:
                    name: hmpps-auth-secrets
              env:
                - name: PROMETHEUS_METRICS
                  value: "off"
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: allocation-rds-instance-output
                      key: rds_instance_address
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: allocation-rds-instance-output
                      key: postgres_password
                - name: POSTGRES_NAME
                  valueFrom:
                    secretKeyRef:
                      name: allocation-rds-instance-output
                      key: postgres_name
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: allocation-rds-instance-output
                      key: postgres_user
                - name: REDIS_URL
                  valueFrom:
                    secretKeyRef:
                      name: elasticache-offender-management-allocation-manager-token-cache-production
                      key: url
          restartPolicy: OnFailure
