# Any environment not explicitly listed will default to false,
# except local and test, where the default will be true
#
feature_flags:
  example_feature:
    staging: true
  rosh_level:
    staging: true
    preprod: true
  new_tiers:
    staging: true
    preprod: true
  rosh_recommendations:
    staging: true
    preprod: true
  prisoner_merges:
    staging: true
    preprod: true
    production: true
  probation_merges:
    staging: true
    preprod: true
    production: true
