apiVersion: apps/v1
kind: Deployment
metadata:
  name: domain-events-consumer
  labels:
    app: domain-events-consumer
  annotations:
    kubernetes.io/change-cause: "deployment"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 20%
    type: RollingUpdate
  selector:
    matchLabels:
      app: domain-events-consumer
  template:
    metadata:
      labels:
        app: domain-events-consumer
    spec:
      serviceAccountName: 'offender-management-allocation-manager'
      containers:
        - name: worker
          image: quay.io/hmpps/offender-management:latest
          imagePullPolicy: Always
          command: ['sh', '-c', 'bin/rake shoryuken:start']
          resources:
            limits:
              memory: "1500Mi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "50m"
          envFrom:
            - configMapRef:
                name: shared-environment
            - secretRef:
                name: allocation-manager-secrets
            - secretRef:
                name: hmpps-auth-secrets
            - secretRef:
                name: domain-events
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: allocation-rds-instance-output
                  key: rds_instance_address
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: allocation-rds-instance-output
                  key: postgres_password
            - name: POSTGRES_NAME
              valueFrom:
                secretKeyRef:
                  name: allocation-rds-instance-output
                  key: postgres_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: allocation-rds-instance-output
                  key: postgres_user
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: elasticache-offender-management-allocation-manager-token-cache-staging
                  key: url
            - name: DOMAIN_EVENTS_TOPIC_ARN
              valueFrom:
                secretKeyRef:
                  name: hmpps-domain-events-topic
                  key: topic_arn
        - name: domain-events-consumer-metrics
          image: quay.io/hmpps/offender-management:latest
          imagePullPolicy: Always
          command: ['sh', '-c', "bundle exec prometheus_exporter --bind 0.0.0.0"]
          ports:
            - containerPort: 9394
          resources:
            limits:
              memory: "200Mi"
              cpu: "50m"
            requests:
              memory: "100Mi"
              cpu: "10m"
