---
custom_templates_config:
  grafana_dashboard:
    enabled: true

cronjobs:
  integration_tests_cleanup:
    enabled: true
  process_movements:
    enabled: true
  recalculate_handover_dates:
    enabled: true
  community_api_import:
    enabled: true
  parole_data_import:
    enabled: true

generic-prometheus-alerts:
  alertSeverity: mpc-alerts-nonprod-dev
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-75ec3c1f26a64520: staging
  elastiCacheAlertsClusterIds:
    cp-5a7bff7c5fe871ef-001: staging cluster node 1
    cp-5a7bff7c5fe871ef-002: staging cluster node 2
  sqsOldestAlertQueueNames:
    - offender-management-staging-domain-events
  sqsNumberAlertQueueNames:
    - offender-management-staging-domain-events-dlq

generic-service:
  ingress:
    hosts:
      - dev.moic.service.justice.gov.uk
    tlsSecretName: allocation-manager-hostname

  allowlist: null

  env:
    ENV_NAME: staging
    SENTRY_CURRENT_ENV: staging
    CACHE_TIMEOUT: "3"
    ALLOCATION_MANAGER_HOST: https://dev.moic.service.justice.gov.uk
    PRISON_API_HOST: https://prison-api-dev.prison.service.justice.gov.uk
    PRISONER_SEARCH_HOST: https://prisoner-search-dev.prison.service.justice.gov.uk
    COMMUNITY_API_HOST: https://community-api-secure.test.delius.probation.hmpps.dsd.io
    COMPLEXITY_API_HOST: https://complexity-of-need-staging.hmpps.service.justice.gov.uk
    NOMIS_OAUTH_HOST: https://sign-in-dev.hmpps.service.justice.gov.uk
    ASSESS_RISKS_AND_NEEDS_API_HOST: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
    MANAGE_POM_CASES_AND_DELIUS_HOST: https://manage-pom-cases-and-delius-dev.hmpps.service.justice.gov.uk
    TIERING_API_HOST: https://hmpps-tier-dev.hmpps.service.justice.gov.uk
    DPS_FRONTEND_COMPONENTS_API_HOST: https://frontend-components-dev.hmpps.service.justice.gov.uk
    DIGITAL_PRISON_SERVICE_HOST: https://digital-dev.prison.service.justice.gov.uk

  namespace_secrets:
    parole-data-import:
      GMAIL_USERNAME: email_username
      GMAIL_PASSWORD: email_password
      PPUD_EMAIL_FROM: email_from
