---
cronjobs:
  mailbox_register_import:
    enabled: true
    schedule: 0 1 * * *
  process_movements:
    enabled: true
    schedule: 0 2 * * *
  recalculate_handover_dates:
    enabled: true
    schedule: 0 3 * * *
  deactivate_unsentenced_cnls:
    enabled: true
    schedule: 45 3 * * *
  early_allocation_suitability_email:
    enabled: true
    schedule: 30 4 * * *
  handover_email:
    enabled: true
    schedule: 4 9 1 * *
  handover_chase_email:
    enabled: true
    schedule: 0 5 * * *
  handover_reminder_email:
    enabled: true
    schedule: 5 0 * * *
  community_api_import:
    enabled: true
    schedule: 0 6 * * *
  parole_data_import:
    enabled: true
    schedule: 15 7 * * *

generic-prometheus-alerts:
  alertSeverity: mpc-alerts-prod
  rdsAlertsDatabases:
    cloud-platform-0fe5d72ea3e106e5: production
  elastiCacheAlertsClusterIds:
    cp-8174bd3acc2d2327-001: production cluster node 1
    cp-8174bd3acc2d2327-002: production cluster node 2
  sqsOldestAlertQueueNames:
    - offender-management-production-domain-events
  sqsNumberAlertQueueNames:
    - offender-management-production-domain-events-dlq

generic-service:
  replicaCount: 5

  ingress:
    hosts:
      - moic.service.justice.gov.uk
    tlsSecretName: allocation-manager-hostname

  postgresDatabaseRestore:
    enabled: true
    schedule: "0 20 * * 3" # At 20:00 on Wednesdays
    jobName: "db-refresh-job"
    env:
      MIGRATIONS_VENDOR: "active_record"
    namespace_secrets:
      allocation-rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      allocation-rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

  env:
    ENV_NAME: production
    SENTRY_CURRENT_ENV: production
    ALLOCATION_MANAGER_HOST: https://moic.service.justice.gov.uk
    PRISON_API_HOST: https://prison-api.prison.service.justice.gov.uk
    PRISONER_SEARCH_HOST: https://prisoner-search.prison.service.justice.gov.uk
    KEYWORKER_API_HOST: https://keyworker-api.prison.service.justice.gov.uk
    COMPLEXITY_API_HOST: https://complexity-of-need.hmpps.service.justice.gov.uk
    NOMIS_OAUTH_HOST: https://sign-in.hmpps.service.justice.gov.uk
    ASSESS_RISKS_AND_NEEDS_API_HOST: https://assess-risks-and-needs.hmpps.service.justice.gov.uk
    MANAGE_POM_CASES_AND_DELIUS_HOST: https://manage-pom-cases-and-delius.hmpps.service.justice.gov.uk
    TIERING_API_HOST: https://hmpps-tier.hmpps.service.justice.gov.uk
    DPS_FRONTEND_COMPONENTS_API_HOST: https://frontend-components.hmpps.service.justice.gov.uk
    DIGITAL_PRISON_SERVICE_HOST: https://digital.prison.service.justice.gov.uk
    PRISON_ALERTS_API_HOST: https://alerts-api.hmpps.service.justice.gov.uk
    MAILBOX_REGISTER_API_HOST: https://manage-custody-mailbox-register-api.hmpps.service.justice.gov.uk
    NOMIS_USER_ROLES_API_HOST: https://nomis-user-roles-api.prison.service.justice.gov.uk

  namespace_secrets:
    allocation-manager-secrets:
      GTM_ID: GTM_ID
